# Generated by Django 6.1 on 2026-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cgpa_cutoff', models.DecimalField(decimal_places=2, max_digits=4)),
                ('interview_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('panel_count', models.PositiveIntegerField()),
                ('priority_tier', models.CharField(max_length=20)),
            ],
        ),
    ]
