# Generated by Django 6.1 on 2026-08-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_room_panel_interview_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='eligible_branches',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
