# Generated by Django 6.1 on 2026-08-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_company_eligible_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='APPLIED', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'company'), name='unique_student_company_applied')],
            },
        ),
    ]
