# Generated by Django 6.1 on 2026-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
